### PR TITLE
Update docs deps

### PR DESCRIPTION
**Pull request by ranjanan**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
We should also update the allowed version to LTS and then change tests to LTS + release.

**Comment by ChrisRackauckas** [comment]
I updated the DNS for CNAME http://polychaos.sciml.ai/

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by ranjanan** [comment]
Looks like `DOCUMENTER_KEY` needs to be set up again. 
```
 Error: Git failed to fetch git@github.com:SciML/PolyChaos.jl.git
│ This can be caused by a DOCUMENTER_KEY variable that is not correctly set up.
│ Make sure that the environment variable is properly set up as a Base64-encoded string
│ of the SSH private key. You may need to re-generate the keys with DocumenterTools.
└ @ Documenter ~/.julia/packages/Documenter/PLD7m/src/Documenter.jl:502
```

**Comment by ranjanan** [comment]
I cannot see a settings button here. Could I get permission to access the settings so I can update the keys here and on travis?

**Comment by ChrisRackauckas** [comment]
I added the repo to the analysis team so you should have access now.

**Comment by ranjanan** [comment]
Ah I am not able to access https://github.com/SciML/PolyChaos.jl/settings/secrets/ though (shows up as 404 for me) . Adding a deployment key also gives me a 404 error instead of success.

**Comment by ChrisRackauckas** [comment]
Why is it needed here? Other docs don't have it and are fine.

**Comment by ranjanan** [comment]
Following these docs: https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#travis-ssh

**Comment by ChrisRackauckas** [comment]
That's for Travis.

**Comment by ranjanan** [comment]
Ohh, was looking at the wrong section. Sorry about that.

**Pull request merged**
